---
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: x-generation
  annotations:
    meta.crossplane.io/maintainer: Crossplane Maintainers <info@crossplane.io>
    meta.crossplane.io/source: github.com/crossplane-contrib/x-generation
    meta.crossplane.io/license: Apache-2.0

    meta.crossplane.io/description: | 
      This Configuration is a starting point to generate compositions 
      from crossplane provider crds.

    meta.crossplane.io/readme: |
      This `Configuration`` is a starting point to generate compositions 
      from crossplane provider crds.

      To learn more checkout the [GitHub
      repo](https://github.com/crossplane-contrib/x-generation/) that you can copy and
      customize to meet the exact needs of your organization!
spec:
  crossplane:
    version: ">=v1.9.0-0"
  dependsOn:
    - provider:  xpkg.upbound.io/crossplane-contrib/provider-aws
      version: ">=v0.32.0"
    - provider:  xpkg.upbound.io/crossplane-contrib/provider-zpa
      version: ">=v0.4.0"
    - provider:  xpkg.upbound.io/upbound/provider-family-aws
      version: ">=v1.4.0"
    - provider:  xpkg.upbound.io/upbound/provider-aws-iam
      version: ">=v1.4.0"
    - provider:  xpkg.upbound.io/upbound/provider-aws-eks
      version: ">=v1.4.0"